# Generated by Django 3.2.6 on 2021-08-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Medium', 'Medium'), ('Later', 'Later')], default='', max_length=6),
            preserve_default=False,
        ),
    ]
